### ISSUE TITLE
Baptême du Seigneur et fête de Saint Joseph

### ISSUE THREAD

**Issue by scriptura** [romain-warnan/calendrier-liturgique#6]
Bonjour,

J'ai vu en épluchant votre code que vous mettiez un degré de préséance de niveau 4 pour le Baptême du Seigneur. Mais il me semble que c'est une fête et non une solennité, ce qui devrait donc la rétrograder au niveau 5 (je ne suis pas sûr de mon coup à 100%).

De même, le test sur la fête de St Joseph me semble erroné : il ne teste que la concurrence avec le jeudi Saint pour reporter dans ce cas la fête au 14 Mars. Alors que la fête est normalement renvoyée dans ce cas au samedi précédant le dimanche des Rameaux (le test se fait sur toute la Semaine Sainte). Voici pour ce deuxième cas la totalité de la règle :

> Saint Joseph, époux. Si la fête tombe un dimanche, autre que le Dimanche des Rameaux, celle-ci est célébrée le jour suivant, généralement le lundi 20 mars, mais seulement si une autre solennité (par exemple, un autre Saint patron de l'Église) n'est pas célébrée durant cette journée. Depuis 2008, si le jour de la Fête de Saint Joseph tombe pendant la Semaine Sainte, la célébration de sa fête est déplacée vers le jour le plus proche possible avant le 19 mars, généralement le samedi précédant la Semaine Sainte.

Voilà, c'est ce que j'ai cru comprendre de votre code et devoir vous dire (perso je fais mon appli sous Node.js).

Bien cordialement.

**Comment by vandenesse** [comment]
Bonjour,

Merci beaucoup pour vos remarques.

Vous avez raison pour le baptême de NSJC, il s'agit seulement d'une fête. Je ne pense pas que cela est de conséquence sur le calcul de la date.

Vous avez également entièrement raison pour la solennité de Saint Joseph, époux de de la TSVM. Il faut clairement vérifier qu'elle ne tombe pas pendant la semaine Sainte et pas seulement le jeudi. Je ne me rappelle pas pourquoi j'ai fait le calcul comme ça.

Je corrigerai cela rapidement.

Encore merci pour vos remarques.

**Comment by scriptura** [comment]
> Bonjour,
> 
> Merci beaucoup pour vos remarques.
> 
> Vous avez raison pour le baptême de NSJC, il s'agit seulement d'une fête. Je ne pense pas que cela est de conséquence sur le calcul de la date.

Je ne pense pas non plus qu'il y ait de conséquence de calcul pour cette fête. C'était juste que cela m'avait mis le doute.

Bonne continuation.
